name: Review Codebase

on:
  push: 
  workflow_dispatch: 

jobs:
  review:
   runs-on: ubuntu-latest
   permissions:
      contents: read
      checks: write
      
   steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      
    - name: Run Checkstyle with Reviewdog
      uses: db-event/action-java-checkstyle@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        level: warning
